# Makefile for an A2F-Linux project

# This project's name
SAMPLE		:= developer_REST_V1

# Custom applcations subdirectories that this project
# needs to build. Edit this list as appropriate for your application.
CUSTOM_APPS	:= ../../A2F/i2c-tools-3.1.0

# Include Make rules applicable to all projects
include ../Rules.make
